[tools]
bun = "latest"
node = "latest"
"npm:prettier" = "latest"
"npm:@openai/codex" = "latest"
"npm:eas-cli" = "latest"
pnpm = "latest"
rust = "stable"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true
